version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pipeline
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  pipeline-app:
    image: pipeline-app   # The same name you built using `docker build -t pipeline-app .`
    container_name: pipeline-app
    depends_on:
      - mysql-db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: pipeline
      DB_USER: testuser
      DB_PASSWORD: testpass
    ports:
      - "8080:8080"

volumes:
  mysql_data:
