spring:
  datasource:
    # url: jdbc:h2:file:./data/testdb
    # username: myuser
    # password: secret
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # Skip DDL until connection confirmed
    show-sql: true

app:
  jwt:
    secret: demoSecretKeyForDevelopment1234567890
    expiration: 86400000