spring:
  application:
    name: pipeline
  

# logging:
#   level:
#     root: DEBUG
---

spring:
  profiles.active: basicAuth
  security:
    user:
      name: admin
      password: "{noop}admin"

---

spring:
  profiles.active: h2InMemory
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
