name: AutoBuild CI

on:
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize]

jobs:
  central-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pipeline Service Validation
        id: pipeline-service-validation
        uses: ./.github/actions/pipeline-service
        with:
          base-ref: ${{github.base_ref}}

      - name: Check for OpenAPI contract violation
        id: is_openapi_contract_violated
        uses: ./.github/actions/openapi-changes
        with:
          base-ref: ${{github.base_ref}}
          has-pipeline-validations-executed: ${{steps.pipeline-service-validation.outputs.has_executed}}
      
      - name: Pipeline UI Validation
        id: pipeline-ui-validation
        uses: ./.github/actions/pipeline-ui
        with:
          base-ref: ${{github.base_ref}}