name: AutoBuild CI

on:
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize]

jobs:
  central-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pipeline Service Validation
        id: pipeline-service-validation
        uses: ./.github/actions/pipeline-service
        with:
          base-ref: ${{github.base_ref}}

      - name: Check for OpenAPI contract violation
        id: is_openapi_contract_violated
        shell: bash
        run: |
          if git diff --quiet HEAD -- apis/openapi-spec && \
              [ -z "$(git status --porcelain -- apis/openapi-spec)" ]; then
            echo "OpenAPI contracts are unchanged/ committed."
          else
            echo "Exiting as OpenAPI contract changes are not committed. Please commit all changes of api contracts if any."
            exit 1
          fi
      
      - name: Pipeline UI Validation
        id: pipeline-ui-validation
        uses: ./.github/actions/pipeline-ui
        with:
          base-ref: ${{github.base_ref}}