name: AutoBuild CI

on:
    pull_request:
        branches: ["main"]
        types: [opened, reopened, synchronize]

jobs:
    central-validation:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Pipeline Service Validation
              id: pipeline-service-validation
              uses: ./.github/actions/pipeline-service
              with:
                base-ref: ${{github.base_ref}}

            - name: Pipeline UI Validation
              id: pipeline-ui-validation
              uses: ./.github/actions/pipeline-ui
              with:
                base-ref: ${{github.base_ref}}