name: Pipeline Service

on:
    pull_request:
        paths:
            - 'pipeline/**'
        branches: ["main"]
        types: [opened, reopened, synchronize]

jobs:
    service-ci:
        uses: ./.github/workflows/_springboot_service_ci.yaml
        with:
            service-path: pipeline