name: Basic Validations

on:
  pull_request:
    branches: ["main"]
    types: [review_requested, ready_for_review]

jobs:
  build:
    name: Basic Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Basic Validation
        run: cd pipeline && mvn --batch-mode clean install
      - name: UI Lint
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install & Lint UI
        run: cd pipeline-ui && npm install && npm run lint
        shell: bash
